export * from "./email.arb";
export * from "./password.arb";
export * from "./search.arb";
export * from "./tuition.arb";
export * from "./document.arb";
export * from "./catalog.arb";
export * from "./user.arb";
export * from "./application.arb";
export * from "./consultation.arb";
